# Copyright (C) 2026, Advanced Micro Devices, Inc. All rights reserved.
# SPDX-License-Identifier: MIT

# INT8 matmul: i8 x i8 -> i32 accumulation.
# L1 budget (with pingpong): 8K(2*A) + 8K(2*B) + 16K(C) = 32KB / 64KB (50%).
#
# Transform script generated by:
#   python examples/matmul_transform.py --l1-m 64 --l1-n 64 --l2-k 64 \
#       --pack-sizes 8 8 8 --accum-type i32 --contract-input-type i16 \
#       -o examples/matmul_i8_m64_n64_k64/transform_aie2p.mlir

import torch
import triton
import triton.language as tl
import sys, os

sys.path.append(os.path.abspath(".."))
import benchmark


@triton.jit
def bare_matmul_i8(
    A,
    B,
    C,
    M: tl.constexpr,
    N: tl.constexpr,
    K: tl.constexpr,
    stride_am: tl.constexpr,
    stride_ak: tl.constexpr,
    stride_bk: tl.constexpr,
    stride_bn: tl.constexpr,
    stride_cm: tl.constexpr,
    stride_cn: tl.constexpr,
    BLOCK_SIZE_M: tl.constexpr,
    BLOCK_SIZE_N: tl.constexpr,
    BLOCK_SIZE_K: tl.constexpr,
):
    pid_m = tl.program_id(0)
    pid_n = tl.program_id(1)

    offs_m = pid_m * BLOCK_SIZE_M + tl.arange(0, BLOCK_SIZE_M)
    offs_n = pid_n * BLOCK_SIZE_N + tl.arange(0, BLOCK_SIZE_N)
    offs_k = tl.arange(0, BLOCK_SIZE_K)

    a_block = tl.load(A + offs_m[:, None] * stride_am + offs_k[None, :] * stride_ak)
    b_block = tl.load(B + offs_k[:, None] * stride_bk + offs_n[None, :] * stride_bn)

    c_block = tl.dot(a_block, b_block)

    tl.store(C + offs_m[:, None] * stride_cm + offs_n[None, :] * stride_cn, c_block)


def bench_matmul_i8(M, N, K, provider):
    device = "cpu"
    dtype_in = torch.int8
    dtype_out = torch.int32
    a = torch.randint(-8, 8, (M, K), device=device, dtype=dtype_in)
    b = torch.randint(-8, 8, (K, N), device=device, dtype=dtype_in)
    c = torch.empty((M, N), device=device, dtype=dtype_out)
    if provider == "torch" or provider == "test":
        c_ref = torch.matmul(a.to(dtype_out), b.to(dtype_out))
    if provider == "triton" or provider == "test":
        grid = lambda META: (
            triton.cdiv(M, META["BLOCK_SIZE_M"]),
            triton.cdiv(N, META["BLOCK_SIZE_N"]),
        )
        compiled_kernel = bare_matmul_i8[grid](
            a,
            b,
            c,
            M,
            N,
            K,
            a.stride(0),
            a.stride(1),
            b.stride(0),
            b.stride(1),
            c.stride(0),
            c.stride(1),
            BLOCK_SIZE_M=256,
            BLOCK_SIZE_N=256,
            BLOCK_SIZE_K=K,
        )
        with open("tt.shared.mlir", "w") as f:
            f.write(str(compiled_kernel.asm["ttsharedir"]))
        if provider == "test":
            torch.testing.assert_close(c, c_ref, atol=0, rtol=0)


if __name__ == "__main__":
    benchmark.select_npu_backend()
    for M in [2**i for i in range(8, 12, 2)]:
        for N in [2**i for i in range(8, 12, 2)]:
            for K in [2**i for i in range(8, 12, 2)]:
                bench_matmul_i8(M, N, K, "test")
                bench_matmul_i8(M, N, K, "test")
