# Copyright (C) 2026, Advanced Micro Devices, Inc. All rights reserved.
# SPDX-License-Identifier: MIT

"""
Parameterized matmul transform dialect script generator.

Generates MLIR Transform dialect scripts for matmul tiling on AIE hardware.
All matmul variants (standard BF16, padded F32 with BF16 emulation, AIE2/AIE2P)
are produced from a single template with numeric parameters.

Parameter names align with mlir-air's programming_examples/matrix_multiplication
conventions (l1_m, l1_n, l2_k) for cross-project consistency.

Usage:
    from amd_triton_npu.backend.matmul_transform import generate_matmul_transform

    # Standard BF16 matmul on AIE2P (Strix)
    mlir = generate_matmul_transform(l1_m=64, l1_n=64, l2_k=64)

    # Padded F32 matmul with BF16 emulation on AIE2P
    mlir = generate_matmul_transform(
        l1_m=64, l1_n=32, l2_k=16, bf16_emulation=True,
    )

    # Standard BF16 matmul on AIE2 (Phoenix)
    mlir = generate_matmul_transform(
        l1_m=64, l1_n=64, l2_k=64, pack_sizes=(4, 4, 8),
    )

    # Integer matmul (i8->i32 accumulation, i16 contract inputs)
    mlir = generate_matmul_transform(
        l1_m=64, l1_n=128, l2_k=256,
        pack_sizes=(8, 8, 8), accum_type="i32", contract_input_type="i16",
    )
"""


def generate_matmul_transform(
    l1_m: int = 64,
    l1_n: int = 64,
    l2_k: int = 64,
    pack_sizes: tuple = (8, 8, 8),
    accum_type: str = "f32",
    contract_input_type: str = None,
    bf16_emulation: bool = False,
) -> str:
    """Generate a matmul transform dialect MLIR script.

    Args:
        l1_m: Per-core L1 tile size in raw M elements. Must be divisible
            by pack_sizes[0]. Each AIE core processes a l1_m x l1_n output
            block.
        l1_n: Per-core L1 tile size in raw N elements. Must be divisible
            by pack_sizes[1].
        l2_k: L3-to-L2 copy tile size along K dimension. Also determines
            the K-reduction tile in packed space (l2_k // pack_sizes[2]).
        pack_sizes: Pack sizes for (M, N, K) dimensions matching the
            hardware microkernel MAC dimensions (mmul_mkn). Typical values:
            (8, 8, 8) for AIE2P, (4, 4, 8) for AIE2.
        accum_type: Element type for the accumulator in vector.contract.
            The vector_type_cast in Phase 11 casts input[2] and output[0]
            to this type. Use "f32" for bf16 matmul, "i32" for i8/i16 matmul.
        contract_input_type: Element type for vector.contract inputs 0,1.
            If set, adds a vector_type_cast to cast the inputs to this type.
            Use "i16" for i8 matmul (AIE2P native i8xi8->i16 MAC with i32
            accumulation). Use "bf16" for f32 data with bf16 emulation.
            If None, inputs are left as-is after vectorization.
        bf16_emulation: Shorthand for contract_input_type="bf16". If True
            and contract_input_type is None, sets contract_input_type="bf16".

    Returns:
        Complete MLIR module string with transform.with_named_sequence.
    """
    pack_m, pack_n, pack_k = pack_sizes

    # bf16_emulation is shorthand for contract_input_type="bf16"
    if bf16_emulation and contract_input_type is None:
        contract_input_type = "bf16"

    assert l1_m % pack_m == 0, (
        f"l1_m={l1_m} must be divisible by pack_m={pack_m}"
    )
    assert l1_n % pack_n == 0, (
        f"l1_n={l1_n} must be divisible by pack_n={pack_n}"
    )
    assert l2_k % pack_k == 0, (
        f"l2_k={l2_k} must be divisible by pack_k={pack_k}"
    )

    # Derived parameters
    forall_l1_m = l1_m // pack_m
    forall_l1_n = l1_n // pack_n
    packed_k_tile = l2_k // pack_k

    # Contract input type cast: cast vector.contract inputs 0,1 to the
    # target type. This matches the hardware MAC unit's native input type.
    # - bf16 matmul: inputs stay bf16 (no cast needed)
    # - bf16 emulation (f32 data): cast inputs f32->bf16
    # - i8 matmul: cast inputs i32->i16 (AIE2P native i8xi8 MAC uses i16 contract)
    input_cast = ""
    if contract_input_type is not None:
        input_cast = f"""
        // Cast vector.contract inputs 0,1 to {contract_input_type}
        // (matches hardware MAC unit native input type)
        %vector_contracts_2 = transform.structured.match ops{{["vector.contract"]}} in %arg1 : (!transform.any_op) -> !transform.any_op
        %result11b = transform.air.vector_type_cast %vector_contracts_2 {{target_element_type = {contract_input_type}, input_indices = [0, 1], output_indices = []}} : (!transform.any_op) -> !transform.any_op
"""

    return f"""\
// Auto-generated by matmul_transform.py — do not edit manually.
// Parameters: l1_m={l1_m}, l1_n={l1_n}, l2_k={l2_k}, \
pack=[{pack_m},{pack_n},{pack_k}], accum={accum_type}, contract_in={contract_input_type}
//
// Copyright (C) 2026, Advanced Micro Devices, Inc. All rights reserved.
// SPDX-License-Identifier: MIT

module attributes {{transform.with_named_sequence}} {{
  transform.named_sequence @__transform_main(%arg1: !transform.any_op {{transform.readonly}}) {{

    //==========================================================================
    // PHASE 1: TILE L3->L2 MEMORY COPIES
    // Tile memref copies for streaming data from DDR (L3) to MemTile (L2).
    //==========================================================================

        %func10 = transform.structured.match ops{{["func.func"]}} in %arg1  : (!transform.any_op) -> !transform.any_op
        %func10_updated = transform.air.convert_memref_copy_to_linalg_copy %func10 : (!transform.any_op) -> !transform.any_op
        %copies = transform.structured.match ops{{["linalg.copy"]}} in %arg1  : (!transform.any_op) -> !transform.any_op
        %copy1, %copy2 = transform.split_handle %copies : (!transform.any_op) -> (!transform.any_op, !transform.any_op)
        %tiled_copy1, %tile_copy_loop1 =
          transform.structured.tile_using_for %copy1 tile_sizes [0, {l2_k}]
          : (!transform.any_op) -> (!transform.any_op, !transform.any_op)
        transform.annotate %tile_copy_loop1 "copy_a_loop" : !transform.any_op
        %tiled_copy2, %tile_copy_loop2 =
          transform.structured.tile_using_for %copy2 tile_sizes [{l2_k}]
          : (!transform.any_op) -> (!transform.any_op, !transform.any_op)
        transform.annotate %tile_copy_loop2 "copy_b_loop" : !transform.any_op

    //==========================================================================
    // PHASE 2: PROMOTE OUTPUT TO L2
    // Allocate output buffer (C) in L2 for accumulation.
    //==========================================================================

        %result_l2 = transform.structured.match ops{{["linalg.fill"]}} in %arg1 : (!transform.any_op) -> !transform.any_op
        %result_l2_buffer, %result_t2_new = transform.structured.bufferize_to_allocation %result_l2
            {{memory_space = 1, bufferize_destination_only, mempcy = "linalg.copy", emit_dealloc}} : !transform.any_op

    //==========================================================================
    // PHASE 3: PACK MATMUL FOR VECTORIZED COMPUTATION
    // Pack [{pack_m}, {pack_n}, {pack_k}], transpose A/B/C, promote C pack to L1.
    //==========================================================================

        %matmul_to_pack = transform.structured.match ops{{["linalg.matmul"]}} in %arg1 : (!transform.any_op) -> !transform.any_op
        %packed = transform.structured.pack %matmul_to_pack packed_sizes = [{pack_m}, {pack_n}, {pack_k}]
          : (!transform.any_op) -> (!transform.any_op)

        // Transpose A: outer_perm [1,0]
        %pack_producer_a = transform.get_producer_of_operand %packed[0]
          : (!transform.any_op) -> (!transform.any_op)
        %packed_a, %pack_a, %empty_unpack_a =
          transform.structured.pack_transpose %pack_producer_a with_compute_op(%packed)
          outer_perm = [1, 0] : (!transform.any_op, !transform.any_op)
          -> (!transform.any_op, !transform.any_op, !transform.any_op)

        // Transpose B: outer_perm [1,0] + inner_perm [1,0]
        %pack_producer_b = transform.get_producer_of_operand %packed_a[1]
          : (!transform.any_op) -> (!transform.any_op)
        %packed_b, %pack_b, %empty_unpack_b =
          transform.structured.pack_transpose %pack_producer_b with_compute_op(%packed_a)
          outer_perm = [1, 0] inner_perm = [1, 0] : (!transform.any_op, !transform.any_op)
          -> (!transform.any_op, !transform.any_op, !transform.any_op)

        // Transpose C: outer_perm [1,0]
        %unpack = transform.get_consumers_of_result %packed_b[0]
          : (!transform.any_op) -> (!transform.any_op)
        %packed_c, %pack_c, %unpack_c =
          transform.structured.pack_transpose %unpack with_compute_op(%packed_b)
          outer_perm = [1, 0] : (!transform.any_op, !transform.any_op)
          -> (!transform.any_op, !transform.any_op, !transform.any_op)

        // Promote C pack to L1
        %output_l1_pack_op_source_buffer, %output_l1_pack_op_new = transform.structured.bufferize_to_allocation %pack_c
            {{memory_space = 2, bufferize_destination_only, memcpy_op = "linalg.copy", emit_dealloc}} : !transform.any_op

        // Annotate for robust matching after K-tiling
        transform.annotate %packed_c "packed_matmul" : !transform.any_op

    //==========================================================================
    // PHASE 4: TILE K REDUCTION AND FUSE PACK OPERATIONS
    // Tile packed K dim by {packed_k_tile} (= {l2_k} raw K elements).
    //==========================================================================

        %tiled_reduction, %outer_for_loop =
          transform.structured.tile_using_for %packed_c tile_sizes [0, 0, {packed_k_tile}]
          : (!transform.any_op) -> (!transform.any_op, !transform.any_op)
        transform.annotate %outer_for_loop "k_reduction_loop" : !transform.any_op

        %fused_lhs_l1_pack, %2 = transform.structured.fuse_into_containing_op %pack_a into %outer_for_loop : (!transform.any_op, !transform.any_op) -> (!transform.any_op, !transform.any_op)
        %fused_rhs_l1_pack, %3 = transform.structured.fuse_into_containing_op %pack_b into %outer_for_loop : (!transform.any_op, !transform.any_op) -> (!transform.any_op, !transform.any_op)

    //==========================================================================
    // PHASE 5: TILE FOR MULTI-CORE PARALLELISM
    // Tile [{forall_l1_m}, {forall_l1_n}, 0] for herd distribution.
    //==========================================================================

        %matmul_1 = transform.structured.match ops{{["linalg.generic"]}} attributes{{packed_matmul}} in %arg1 : (!transform.any_op) -> !transform.any_op
        %tiled_matmul_1, %inner_forall =
          transform.structured.tile_using_forall %matmul_1 tile_sizes [{forall_l1_m}, {forall_l1_n}, 0] : (!transform.any_op) -> (!transform.any_op, !transform.any_op)
        transform.annotate %inner_forall "compute_forall" : !transform.any_op
        transform.annotate %tiled_matmul_1 "matmul_compute" : !transform.any_op

        %fused_lhs_l1_pack2, %6 = transform.structured.fuse_into_containing_op %fused_lhs_l1_pack into %inner_forall : (!transform.any_op, !transform.any_op) -> (!transform.any_op, !transform.any_op)
        %fused_rhs_l1_pack2, %7 = transform.structured.fuse_into_containing_op %fused_rhs_l1_pack into %inner_forall : (!transform.any_op, !transform.any_op) -> (!transform.any_op, !transform.any_op)

        %func_2 = transform.structured.match ops{{["func.func"]}} in %arg1 : (!transform.any_op) -> !transform.any_op
        transform.apply_patterns to %func_2 {{
            transform.apply_patterns.linalg.tiling_canonicalization
            transform.apply_patterns.scf.for_loop_canonicalization
            transform.apply_patterns.canonicalization
        }} : !transform.any_op
        transform.apply_cse to %func_2 : !transform.any_op

    //==========================================================================
    // PHASE 6: PROMOTE INPUTS TO L1 AND TILE PROLOGUE/EPILOGUE
    //==========================================================================

        // Promote A and B to L1
        %buffer_a, %new_a = transform.structured.bufferize_to_allocation %fused_lhs_l1_pack2
          {{memory_space = 2, bufferize_destination_only, emit_dealloc}} : !transform.any_op
        %buffer_b, %new_b = transform.structured.bufferize_to_allocation %fused_rhs_l1_pack2
          {{memory_space = 2, bufferize_destination_only, emit_dealloc}} : !transform.any_op

        // Prologue: fill -> generalize -> interchange -> tile for herd
        %fill_op = transform.structured.match ops{{["linalg.fill"]}} in %arg1 : (!transform.any_op) -> !transform.any_op
        %generic_fill_op = transform.structured.generalize %fill_op
            : (!transform.any_op) -> !transform.any_op
        transform.annotate %generic_fill_op "init_fill" : !transform.any_op
        %interchanged_fill_op = transform.structured.interchange %generic_fill_op
          iterator_interchange = [1, 0, 2, 3]
          : (!transform.any_op) -> !transform.any_op
        %prologue_tiled_fill, %prologue_forall =
          transform.structured.tile_using_forall %interchanged_fill_op tile_sizes [{forall_l1_m}, {forall_l1_n}]
            : (!transform.any_op) -> (!transform.any_op, !transform.any_op)
        transform.annotate %prologue_forall "prologue_forall" : !transform.any_op

        // Epilogue: unpack -> tile for L2 write-back
        %unpack_op = transform.structured.match ops{{["linalg.unpack"]}} in %arg1 : (!transform.any_op) -> !transform.any_op
        %epilogue_tiled_unpack, %epilogue_forall =
          transform.structured.tile_using_forall %unpack_op tile_sizes [{l1_m}, {l1_n}]
            : (!transform.any_op) -> (!transform.any_op, !transform.any_op)
        transform.annotate %epilogue_forall "epilogue_forall" : !transform.any_op

        %func_3 = transform.structured.match ops{{["func.func"]}} in %arg1 : (!transform.any_op) -> !transform.any_op
        transform.apply_patterns to %func_3 {{
            transform.apply_patterns.linalg.tiling_canonicalization
            transform.apply_patterns.scf.for_loop_canonicalization
            transform.apply_patterns.canonicalization
        }} : !transform.any_op
        transform.apply_cse to %func_3 : !transform.any_op

    //==========================================================================
    // PHASE 7: BUFFERIZATION AND MEMORY OPTIMIZATION
    //==========================================================================

        %func_op = transform.structured.match ops{{["func.func"]}} in %arg1 : (!transform.any_op) -> !transform.any_op
        %func_bufferized = transform.bufferization.one_shot_bufferize %func_op : (!transform.any_op) -> !transform.any_op

        %func6 = transform.structured.match ops{{["func.func"]}} in %arg1 : (!transform.any_op) -> !transform.any_op
        transform.apply_patterns to %func6 {{
            transform.apply_patterns.linalg.tiling_canonicalization
            transform.apply_patterns.scf.for_loop_canonicalization
            transform.apply_patterns.canonicalization
        }} : !transform.any_op
        transform.apply_cse to %func6 : !transform.any_op
        transform.apply_patterns to %func6 {{
            transform.apply_patterns.canonicalization
        }} : !transform.any_op
        %func_op_updated = transform.air.remove_uninitialized_copy %func6 : (!transform.any_op) -> !transform.any_op
        %func_op_updated_1 = transform.air.eliminate_cascade_memcpy %func_op_updated : (!transform.any_op) -> !transform.any_op

    //==========================================================================
    // PHASE 8: FUSE LOOPS FOR L2 PINGPONG BUFFERING
    //==========================================================================

        %for_loop_copy_1 = transform.structured.match ops{{["scf.for"]}} attributes{{copy_a_loop}} in %arg1 : (!transform.any_op) -> !transform.any_op
        %for_loop_copy_2 = transform.structured.match ops{{["scf.for"]}} attributes{{copy_b_loop}} in %arg1 : (!transform.any_op) -> !transform.any_op
        %main_for_loop = transform.structured.match ops{{["scf.for"]}} attributes{{k_reduction_loop}} in %arg1 : (!transform.any_op) -> !transform.any_op
        %main_for_loop_norm = transform.air.normalize_for_bounds %main_for_loop : (!transform.any_op) -> !transform.any_op
        transform.apply_cse to %func_op_updated_1 : !transform.any_op
        %fused_for_loop_2 = transform.loop.fuse_sibling %for_loop_copy_2 into %main_for_loop_norm
          : (!transform.any_op, !transform.any_op) -> !transform.any_op
        %fused_for_loop_1 = transform.loop.fuse_sibling %for_loop_copy_1 into %fused_for_loop_2
          : (!transform.any_op, !transform.any_op) -> !transform.any_op

    //==========================================================================
    // PHASE 9: TILE FOR VECTORIZATION
    //==========================================================================

        %generic1 = transform.structured.match ops{{["linalg.generic"]}} attributes{{init_fill}} in %arg1 : (!transform.any_op) -> !transform.any_op
        %generic2 = transform.structured.match ops{{["linalg.generic"]}} attributes{{matmul_compute}} in %arg1 : (!transform.any_op) -> !transform.any_op
        %inner_most_generics, %vec_loops:3 =
          transform.structured.tile_using_for %generic2 tile_sizes [2, 2, 1, 0, 0, 0]
          : (!transform.any_op) -> (!transform.any_op, !transform.any_op, !transform.any_op, !transform.any_op)

        %inner_most_matmul_to_unroll, %vec_loops_to_unroll:2 =
          transform.structured.tile_using_for %inner_most_generics tile_sizes [1, 1, 0, 0, 0, 0]
          : (!transform.any_op) -> (!transform.any_op, !transform.any_op, !transform.any_op)
        transform.loop.unroll %vec_loops_to_unroll#1 {{factor = 2}} : !transform.any_op
        transform.loop.unroll %vec_loops_to_unroll#0 {{factor = 2}} : !transform.any_op

        %inner_most_fills, %vec_fill_loops:2 =
          transform.structured.tile_using_for %generic1 tile_sizes [1, 1, 0, 0]
          : (!transform.any_op) -> (!transform.any_op, !transform.any_op, !transform.any_op)

    //==========================================================================
    // PHASE 10: CONVERT TO AIE HERDS AND VECTORIZE
    //==========================================================================

        %forall1 = transform.structured.match ops{{["scf.forall"]}} attributes{{prologue_forall}} in %arg1 : (!transform.any_op) -> !transform.any_op
        %forall2 = transform.structured.match ops{{["scf.forall"]}} attributes{{compute_forall}} in %arg1 : (!transform.any_op) -> !transform.any_op
        %forall3 = transform.structured.match ops{{["scf.forall"]}} attributes{{epilogue_forall}} in %arg1 : (!transform.any_op) -> !transform.any_op
        %parallel1 = transform.loop.forall_to_parallel %forall1  : (!transform.any_op) -> !transform.any_op
        %herd1 = transform.air.par_to_herd %parallel1 : (!transform.any_op) -> !transform.any_op
        transform.annotate %herd1 "prologue_herd" : !transform.any_op
        %parallel2 = transform.loop.forall_to_parallel %forall2  : (!transform.any_op) -> !transform.any_op
        %herd2 = transform.air.par_to_herd %parallel2 : (!transform.any_op) -> !transform.any_op
        transform.annotate %herd2 "compute_herd" : !transform.any_op
        %parallel3 = transform.loop.forall_to_parallel %forall3  : (!transform.any_op) -> !transform.any_op
        %herd3 = transform.air.par_to_herd %parallel3 : (!transform.any_op) -> !transform.any_op
        transform.annotate %herd3 "epilogue_herd" : !transform.any_op

        %herds = transform.structured.match ops{{["air.herd"]}} in %arg1 : (!transform.any_op) -> !transform.any_op
        %vectorized_herds = transform.air.herd_vectorize %herds : (!transform.any_op) -> !transform.any_op

        %func7 = transform.structured.match ops{{["func.func"]}} in %arg1 : (!transform.any_op) -> !transform.any_op
        transform.apply_patterns to %func7 {{
            transform.apply_patterns.linalg.tiling_canonicalization
            transform.apply_patterns.scf.for_loop_canonicalization
            transform.apply_patterns.canonicalization
            transform.apply_patterns.memref.fold_memref_alias_ops
        }} : !transform.any_op
        %func_fold_1 = transform.structured.match ops{{["func.func"]}} in %arg1 : (!transform.any_op) -> !transform.any_op
        %func_folded_1 = transform.air.fold_unit_extent_dims %func_fold_1 : (!transform.any_op) -> !transform.any_op

        %func7_rematch = transform.structured.match ops{{["func.func"]}} in %arg1 : (!transform.any_op) -> !transform.any_op
        %func1_optimized = transform.air.eliminate_redundant_vector_transfers %func7_rematch : (!transform.any_op) -> !transform.any_op

    //==========================================================================
    // PHASE 11: HOIST LOOP-INVARIANT VECTOR TRANSFERS
    //==========================================================================

        %herd2_1 = transform.structured.match ops{{["air.herd"]}} attributes{{compute_herd}} in %arg1 : (!transform.any_op) -> !transform.any_op
        %scf_fors_1 = transform.structured.match ops{{["scf.for"]}} in %herd2_1 : (!transform.any_op) -> !transform.any_op
        %innermost_for, %outer_fors = transform.split_handle %scf_fors_1 {{overflow_result = 1}} : (!transform.any_op) -> (!transform.any_op, !transform.any_op)

        // Cast accumulator (input[2]) and output[0] to {accum_type}
        %vector_contracts = transform.structured.match ops{{["vector.contract"]}} in %arg1 : (!transform.any_op) -> !transform.any_op
        %result11 = transform.air.vector_type_cast %vector_contracts {{target_element_type = {accum_type}, input_indices = [2], output_indices = [0]}} : (!transform.any_op) -> !transform.any_op
{input_cast}\

        %innermost_for_updated_3 = transform.air.hoist_loop_invariant_transfers %herd2_1, %innermost_for : (!transform.any_op, !transform.any_op) -> !transform.any_op

    //==========================================================================
    // PHASE 12: FINAL LOOP OPTIMIZATIONS
    //==========================================================================

        %innermost_for_updated_4 = transform.air.flatten_for_iter_args %innermost_for_updated_3 : (!transform.any_op) -> !transform.any_op
        %innermost_for_updated_5 = transform.air.hoist_vector_transfer_pointers %innermost_for_updated_4 : (!transform.any_op) -> !transform.any_op

        %func9 = transform.structured.match ops{{["func.func"]}} in %arg1 : (!transform.any_op) -> !transform.any_op
        transform.apply_patterns to %func9 {{
            transform.apply_patterns.linalg.tiling_canonicalization
            transform.apply_patterns.scf.for_loop_canonicalization
            transform.apply_patterns.canonicalization
            transform.apply_patterns.memref.fold_memref_alias_ops
        }} : !transform.any_op
        %func_fold_2 = transform.structured.match ops{{["func.func"]}} in %arg1 : (!transform.any_op) -> !transform.any_op
        %func_folded_2 = transform.air.fold_unit_extent_dims %func_fold_2 : (!transform.any_op) -> !transform.any_op

    transform.yield
  }}
}}
"""


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(
        description="Generate matmul transform dialect MLIR scripts"
    )
    parser.add_argument(
        "--l1-m", type=int, default=64, help="L1 per-core tile M (default: 64)"
    )
    parser.add_argument(
        "--l1-n", type=int, default=64, help="L1 per-core tile N (default: 64)"
    )
    parser.add_argument(
        "--l2-k", type=int, default=64, help="L2 tile K (default: 64)"
    )
    parser.add_argument(
        "--pack-sizes",
        type=int,
        nargs=3,
        default=[8, 8, 8],
        help="Pack sizes for M N K (default: 8 8 8)",
    )
    parser.add_argument(
        "--accum-type",
        type=str,
        default="f32",
        choices=["f32", "i32", "i64"],
        help="Accumulator element type (default: f32)",
    )
    parser.add_argument(
        "--contract-input-type",
        type=str,
        default=None,
        choices=["bf16", "i16", "i32"],
        help="Cast vector.contract inputs to this type (e.g., i16 for i8 matmul)",
    )
    parser.add_argument(
        "--bf16-emulation",
        action="store_true",
        help="Shorthand for --contract-input-type bf16",
    )
    parser.add_argument(
        "-o", "--output", type=str, default=None, help="Output file (default: stdout)"
    )

    args = parser.parse_args()
    result = generate_matmul_transform(
        l1_m=args.l1_m,
        l1_n=args.l1_n,
        l2_k=args.l2_k,
        pack_sizes=tuple(args.pack_sizes),
        accum_type=args.accum_type,
        contract_input_type=args.contract_input_type,
        bf16_emulation=args.bf16_emulation,
    )
    if args.output:
        with open(args.output, "w") as f:
            f.write(result)
        print(f"Written to {args.output}")
    else:
        print(result)
